namespace: rhjhunt
name: towerhealth
version: 1.0.0
readme: README.md
authors:
  - "Jacob Hunt <jhunt@redhat.com>"
description: Collection to provide a general health check of an Ansible Tower installation
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags:
  - tower
  - healthcheck
  - health
  - check
  - awx
dependencies:
  "awx.awx": "*"
  "community.general": "*"
repository: "https://github.com/rhjhunt/towerhealth"
documentation: "https://github.com/rhjhunt/towerhealth/wiki"
homepage: "https://github.com/rhjhunt/towerhealth/wiki"
issues: "https://github.com/rhjhunt/towerhealth/issues"
build_ignore:
  - '.vale.ini'
  - '.yamllint'
  - '.markdownlint.json'
  - '.github'
  - '.gitignore'
