---
- name: Check replication
  block:

  - name: Set pg_bash fact
    set_fact:
      pg_bash: ""
    when: pg_bash is not defined

  - name: check replication status and latency
    command: '{{ pg_bash }} psql -U postgres -t -c "select extract(epoch from now() - pg_last_xact_replay_timestamp());"'
    register: replication_latency
    changed_when: false

  - name: extract datetime
    debug:
      msg: "Replication latency is {{ replication_latency.stdout | float }}"
    failed_when: replication_latency.stdout | float > replication_time_threshold

  - name: ensure replica is in recovery mode
    command: '{{ pg_bash }} psql -U postgres -t -c "select pg_is_in_recovery();"'
    register: recovery_mode
    changed_when: false

  - name: check recovery mode is set to true on replica(s)
    debug:
      msg: "Recovery mode is {{ (recovery_mode.stdout.strip() == 't') | ternary('TRUE', 'FALSE') }}"
    failed_when: recovery_mode.stdout.strip() != 't'

  when: not tower_db_external
  become: true
  become_user: postgres