galaxy_info:
  author: Jacob Hunt
  description: Role to provide a healthcheck to the Ansible Tower proxy

  license: GPL-3.0-or-later

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8

galaxy_tags:
  - tower
  - ansibletower
  - proxy
  - healthcheck

dependencies: []
