---
- name: Gather information from Tower with password authentication
  block:
    - name: Get the status from the ping API call
      ansible.builtin.set_fact:
        tower_ping: "{{ lookup('ansible.tower.tower_api', 'ping', host=tower_host, username=tower_user, password=tower_password, verify_ssl=validate_certs) }}"

    - name: Get the settings from settings API call
      ansible.builtin.set_fact:
        tower_settings: "{{ lookup('ansible.tower.tower_api', 'settings/all', host=tower_host, username=tower_user, password=tower_password, verify_ssl=validate_certs) }}"
  when:
    - tower_password != ""
    - tower_oauth_token == ""

- name: Gather information from Tower with Oauth authentication
  block:
    - name: Get the status from the ping API call
      ansible.builtin.set_fact:
        tower_ping: "{{ lookup('ansible.tower.tower_api', 'ping', host=tower_host, username=tower_user, oauth_token=tower_oauth_token, verify_ssl=validate_certs) }}"

    - name: Get the settings from settings API call
      ansible.builtin.set_fact:
        tower_settings: "{{ lookup('ansible.tower.tower_api', 'settings/all', host=tower_host, username=tower_user, oauth_token=tower_oauth_token, verify_ssl=validate_certs) }}"
  when:
    - tower_oauth_token != ""