---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: db00
    groups:
      - database
      - database_all
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 0.0.0.0:5432:5432/tcp
    privileged: true
    pre_build_image: true
  - name: db01
    groups:
      - database_replica
      - database_all
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 0.0.0.0:5433:5432/tcp
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      database:
        db_server: true
      database_replica:
        db_replica: true
      database_all:
        pgsqlrep_password: changeme
verifier:
  name: ansible
